import argparse
import os
from typing import Tuple

import torch
from loguru import logger
from PIL import Image
from torchvision import transforms

from models.qwen import Qwen2VLV7BModel
from utils.transforms import get_transforms

def load_image(image_path: str, transform: transforms.Compose) -> torch.Tensor:
    """
    Loads an image and applies the given transformation.

    Args:
        image_path (str): Path to the image file.
        transform (transforms.Compose): Transformation to apply to the image.

    Returns:
        torch.Tensor: Transformed image tensor with a batch dimension.
    """
    image = Image.open(image_path).convert("RGB")
    image_tensor = transform(image)
    return image_tensor.unsqueeze(0)  # add batch dimension

def process_output(generated_text: str) -> Tuple[str, str]:
    """
    Splits the generated text into reasoning and final decision.

    Args:
        generated_text (str): The text generated by the model.

    Returns:
        Tuple[str, str]: A tuple of (reasoning, final_decision).
    """
    if "Final Decision:" in generated_text:
        reasoning, final = generated_text.split("Final Decision:", 1)
        return reasoning.strip(), final.strip()
    else:
        return generated_text.strip(), ""

def save_report(report_text: str, output_path: str) -> None:
    """
    Saves the report text to a file.

    Args:
        report_text (str): The report text to be saved.
        output_path (str): Path to the output text file.
    """
    with open(output_path, "w") as f:
        f.write(report_text)
    logger.info(f"Report saved to {output_path}")

def main(image_path: str, checkpoint_dir: str, results_dir: str, augment: bool = False) -> None:
    """
    Processes a new image through the VLM pipeline using a trained model checkpoint and saves the generated report.

    The workflow is as follows:
      1. Image Processing: The image is fed through the vision encoder to extract visual features.
      2. Feature Fusion: These features are projected into the language model’s space via the fusion module.
      3. Text Generation: The language model generates text using the fused features as a prompt.
      4. Output Parsing: The generated text is split into reasoning and final decision.
      5. Report Saving: The complete report is saved to a text file.

    Args:
        image_path (str): Path to the input image.
        checkpoint_dir (str): Path to the trained model checkpoint.
        results_dir (str): Directory where the report text file will be saved.
        augment (bool): Whether to use image augmentation.
    """
    os.makedirs(results_dir, exist_ok=True)
    logger.info(f"Loading trained Qwen2.5-7B-bnb-4bit model from checkpoint: {checkpoint_dir}")
    # Load the model checkpoint from the specified directory.
    model_wrapper = Qwen2VLV7BModel(model_name=checkpoint_dir)
    model = model_wrapper.model
    tokenizer = model_wrapper.tokenizer

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()

    logger.info(f"Loading image from path: {image_path}")
    transform = get_transforms(augment)
    image_tensor = load_image(image_path, transform).to(device)

    logger.debug("Running inference on the image...")
    with torch.no_grad():
        # Here we assume that the model's generate method has been adapted to take the image inputs via a fusion pipeline.
        generated_texts = model_wrapper.generate(input_ids=None, attention_mask=None, max_length=256)
        
        generated_text = generated_texts[0] if isinstance(generated_texts, list) else generated_texts

    reasoning, final_decision = process_output(generated_text)
    report = (
        f"Reasoning: {reasoning}\nFinal Decision: {final_decision}\n"
    )
    
    output_file = os.path.join(results_dir, "report.txt")
    save_report(report, output_file)
    logger.info(f"Inference complete. Report:\n {report}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run inference on a new image using the trained Qwen2.5-7B-bnb-4bit model and save the report.")
    parser.add_argument("--image_path", type=str, required=True, help="Path to the input image.")
    parser.add_argument("--checkpoint_dir", type=str, default="results", help="Directory containing the trained model checkpoint.")
    parser.add_argument("--results_dir", type=str, default="reports", help="Directory to save the report text file.")
    parser.add_argument("--augment", action="store_true", help="Whether to apply augmentation transforms.")
    args = parser.parse_args()
    main(image_path=args.image_path, checkpoint_dir=args.checkpoint_dir, results_dir=args.results_dir, augment=args.augment)
